/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef HelloSevice_H
#define HelloSevice_H

#include <thrift/TDispatchProcessor.h>
#include "hello_types.h"



class HelloSeviceIf {
 public:
  virtual ~HelloSeviceIf() {}
  virtual void say_hello(Response& _return, const Request& req) = 0;
};

class HelloSeviceIfFactory {
 public:
  typedef HelloSeviceIf Handler;

  virtual ~HelloSeviceIfFactory() {}

  virtual HelloSeviceIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(HelloSeviceIf* /* handler */) = 0;
};

class HelloSeviceIfSingletonFactory : virtual public HelloSeviceIfFactory {
 public:
  HelloSeviceIfSingletonFactory(const boost::shared_ptr<HelloSeviceIf>& iface) : iface_(iface) {}
  virtual ~HelloSeviceIfSingletonFactory() {}

  virtual HelloSeviceIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(HelloSeviceIf* /* handler */) {}

 protected:
  boost::shared_ptr<HelloSeviceIf> iface_;
};

class HelloSeviceNull : virtual public HelloSeviceIf {
 public:
  virtual ~HelloSeviceNull() {}
  void say_hello(Response& /* _return */, const Request& /* req */) {
    return;
  }
};

typedef struct _HelloSevice_say_hello_args__isset {
  _HelloSevice_say_hello_args__isset() : req(false) {}
  bool req;
} _HelloSevice_say_hello_args__isset;

class HelloSevice_say_hello_args {
 public:

  HelloSevice_say_hello_args() {
  }

  virtual ~HelloSevice_say_hello_args() throw() {}

  Request req;

  _HelloSevice_say_hello_args__isset __isset;

  void __set_req(const Request& val) {
    req = val;
  }

  bool operator == (const HelloSevice_say_hello_args & rhs) const
  {
    if (!(req == rhs.req))
      return false;
    return true;
  }
  bool operator != (const HelloSevice_say_hello_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const HelloSevice_say_hello_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class HelloSevice_say_hello_pargs {
 public:


  virtual ~HelloSevice_say_hello_pargs() throw() {}

  const Request* req;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _HelloSevice_say_hello_result__isset {
  _HelloSevice_say_hello_result__isset() : success(false) {}
  bool success;
} _HelloSevice_say_hello_result__isset;

class HelloSevice_say_hello_result {
 public:

  HelloSevice_say_hello_result() {
  }

  virtual ~HelloSevice_say_hello_result() throw() {}

  Response success;

  _HelloSevice_say_hello_result__isset __isset;

  void __set_success(const Response& val) {
    success = val;
  }

  bool operator == (const HelloSevice_say_hello_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const HelloSevice_say_hello_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const HelloSevice_say_hello_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _HelloSevice_say_hello_presult__isset {
  _HelloSevice_say_hello_presult__isset() : success(false) {}
  bool success;
} _HelloSevice_say_hello_presult__isset;

class HelloSevice_say_hello_presult {
 public:


  virtual ~HelloSevice_say_hello_presult() throw() {}

  Response* success;

  _HelloSevice_say_hello_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class HelloSeviceClient : virtual public HelloSeviceIf {
 public:
  HelloSeviceClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
    piprot_(prot),
    poprot_(prot) {
    iprot_ = prot.get();
    oprot_ = prot.get();
  }
  HelloSeviceClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :
    piprot_(iprot),
    poprot_(oprot) {
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void say_hello(Response& _return, const Request& req);
  void send_say_hello(const Request& req);
  void recv_say_hello(Response& _return);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class HelloSeviceProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<HelloSeviceIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (HelloSeviceProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_say_hello(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  HelloSeviceProcessor(boost::shared_ptr<HelloSeviceIf> iface) :
    iface_(iface) {
    processMap_["say_hello"] = &HelloSeviceProcessor::process_say_hello;
  }

  virtual ~HelloSeviceProcessor() {}
};

class HelloSeviceProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  HelloSeviceProcessorFactory(const ::boost::shared_ptr< HelloSeviceIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< HelloSeviceIfFactory > handlerFactory_;
};

class HelloSeviceMultiface : virtual public HelloSeviceIf {
 public:
  HelloSeviceMultiface(std::vector<boost::shared_ptr<HelloSeviceIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~HelloSeviceMultiface() {}
 protected:
  std::vector<boost::shared_ptr<HelloSeviceIf> > ifaces_;
  HelloSeviceMultiface() {}
  void add(boost::shared_ptr<HelloSeviceIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void say_hello(Response& _return, const Request& req) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->say_hello(_return, req);
    }
    ifaces_[i]->say_hello(_return, req);
    return;
  }

};



#endif
